# Generated by Django 4.0 on 2022-01-03 18:36

import App_Login.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='/profile/default.png', upload_to=App_Login.models.upload_image),
        ),
    ]
