# Generated by Django 4.0 on 2022-01-06 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0002_alter_userprofile_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=260)),
                ('amount', models.IntegerField()),
                ('plan_id', models.CharField(max_length=260)),
            ],
            options={
                'verbose_name_plural': 'Plans',
                'db_table': 'Plans',
            },
        ),
        migrations.CreateModel(
            name='UserPlans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='App_Login.plans')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofileplan', to='App_Login.userprofile')),
            ],
            options={
                'verbose_name_plural': 'User Plans',
                'db_table': 'User Plans',
            },
        ),
    ]
