# Generated by Django 4.0 on 2022-01-12 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0004_alter_userplans_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plans',
            name='amount',
            field=models.FloatField(),
        ),
    ]
