# Generated by Django 4.0 on 2022-01-12 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0005_alter_plans_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='plans',
            name='plan_description',
            field=models.TextField(blank=True),
        ),
    ]
