# Generated by Django 4.0 on 2022-01-12 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0006_plans_plan_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplans',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
