# Generated by Django 4.0 on 2022-01-13 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0007_userplans_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplans',
            name='billing_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userplans',
            name='billing_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
