# Generated by Django 4.0 on 2022-01-13 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0008_userplans_billing_address_userplans_billing_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plans',
            name='plan_id',
            field=models.CharField(max_length=260, unique=True),
        ),
    ]
